parser: babel-eslint

env:
  browser: true
  commonjs: true
  es2020: true
  node: true

extends:
  - google
  - plugin:jsdoc/recommended

parserOptions:
  ecmaVersion: 11
  sourceType: module

ignorePatterns:
  - 'dist/**'
  - 'dev/**'
  - 'externs.js'

rules:
  'jsdoc/require-file-overview': 
    - error
    - {
        tags: {
          file: {
            initialCommentsOnly: true,
            mustExist: true,
            preventDuplicates: true,
          },
          license: {
            initialCommentsOnly: true,
            mustExist: true,
            preventDuplicates: true,
          },
        }
      }

  require-jsdoc:
    - error
    - require:
        ClassDeclaration: true
        FunctionDeclaration: true
        MethodDefinition: true
        FunctionExpression: false
        ArrowFunctionExpression: false

  operator-linebreak:
    - error
    - before

  object-curly-spacing:
    - error
    - always

settings:
  jsdoc:
    mode: closure