language: node_js
node_js:
  - 14
  - lts/*

# Install necessary local/global deps.
install: npm run gnv-install-dev

script:

  # Build the release CLI at dist/cli.cjs using the dev CLI source at
  # dev/cli.js.
  - gnv-dev build

  # Check that the compiled gnv can run with only global deps.
  ## Remove all deps. 
  - npm uninstall * -f --no-save --silent
  - npm uninstall * -fg --no-save --silent
  ## Install release dependencies only.
  - npm run gnv-install
  ## Run gnv and test.
  - gnv
  
  # Re-build the release CLI *using* the freshly-built release CLI.
  - gnv build
  # Run gnv and test.
  - gnv