language: node_js
node_js:
  - 14
  - lts/*

# Install necessary local/global deps.
install: npm run get-deps

script:

  # Build the release CLI at dist/cli.cjs using the dev CLI source at
  # dev/cli.js.
  - gnv-dev build

  # Check that the compiled gnv can run without deps.
  - echo 'Testing without deps...'
  - npm uninstall * -f --no-save --silent
  - npm uninstall -fg --no-save --silent *
  - gnv
  
  # Re-build the release CLI *using* the freshly-built release CLI.
  - gnv build