language: node_js
node_js:
  - 14
  - lts/*

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"

install: yarn boot
script:
  - gnv-dev build
  # - gnv build