language: node_js
node_js:
  - 14
  - lts/*

# Install necessary local/global deps.
install: npm run get-deps

# Test the dev and release CLIs.
script:

  # Build the release CLI at dist/cli.cjs using the dev CLI source at
  # dev/cli.js.
  - gnv-dev build
  
  # Re-build the release CLI *using* the freshly-built release CLI.
  - gnv build